version: '3.8'
services:
  user-service:
    build: ./user-service
    ports:
      - "3003:3003"
    depends_on:
      - mongo
  news-service:
    build: ./news-service
    ports:
      - "3004:3004"
    depends_on:
      - rabbitmq
  notification-service:
    build: ./notification-service
    ports:
      - "3002:3002"
    depends_on:
      - news-service
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
  mongo:
    image: mongo
    ports:
      - "27017:27017"
