version: '3.8'

services:
  user-service:
    build: ./user-service
    ports:
      - "3003:3003"
    env_file:
      - ./user-service/.env
    networks:
      - dapr-network
    labels:
      - "dapr.io/enabled=true"
      - "dapr.io/app-id=user-service"
      - "dapr.io/app-port=3003"
      - "dapr.io/config=statestore-config"
    depends_on:
      - mongo

  news-service:
    build: ./news-service
    ports:
      - "3004:3004"
    env_file:
      - ./news-service/.env
    networks:
      - dapr-network
    labels:
      - "dapr.io/enabled=true"
      - "dapr.io/app-id=news-service"
      - "dapr.io/app-port=3004"
      - "dapr.io/config=statestore-config"

  notification-service:
    build: ./notification-service
    ports:
      - "3002:3002"
    networks:
      - dapr-network
    labels:
      - "dapr.io/enabled=true"
      - "dapr.io/app-id=notification-service"
      - "dapr.io/app-port=3002"
      - "dapr.io/config=statestore-config"

  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - dapr-network

networks:
  dapr-network:
    driver: bridge
