version: '3.8'
services:
  user-service:
    build: ./user-service
    ports:
      - "3003:3003"
    depends_on:
      - mongo
    labels:
      - "dapr.io/enabled=true"
      - "dapr.io/app-id=user-service"
      - "dapr.io/app-port=3003"

  news-service:
    build: ./news-service
    ports:
      - "3004:3004"
    depends_on:
      - rabbitmq
    labels:
      - "dapr.io/enabled=true"
      - "dapr.io/app-id=news-service"
      - "dapr.io/app-port=3004"

  notification-service:
    build: ./notification-service
    ports:
      - "3002:3002"
    depends_on:
      - news-service
    labels:
      - "dapr.io/enabled=true"
      - "dapr.io/app-id=notification-service"
      - "dapr.io/app-port=3002"

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"

  mongo:
    image: mongo
    ports:
      - "27017:27017"
