version: '3.8'
services:
  user-service:
    build: ./user-service
    ports:
      - "3000:3000"
    depends_on:
      - user-db
    networks:
      - user-network

  user-db:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - user-network

  news-service:
    build: ./news-service
    ports:
      - "3001:3001"
    networks:
      - user-network

  notification-service:
    build: ./notification-service
    ports:
      - "3002:3002"
    networks:
      - user-network

networks:
  user-network:
    driver: bridge
