version: '3.8'

services:
  user-service:
    build: ./user-service
    ports:
      - "3000:3000"
    depends_on:
      - user-db

  news-service:
    build: ./news-service
    ports:
      - "3001:3001"

  notification-service:
    build: ./notification-service
    ports:
      - "3002:3002"

  user-db:
    image: mongo
    ports:
      - "27017:27017"
