version: '3.8'

services:
  user-service:
    build: ./user-service
    ports:
      - "3003:3003"
    env_file:
      - .env

  news-service:
    build: ./news-service
    ports:
      - "3004:3004"
    env_file:
      - .env

  # mongo-service:
  #   image: mongo
  #   ports:
  #     - "27017:27017"
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: example
