version: '3.8'

services:
  user-service:
    build: ./user-service
    ports:
      - "3003:3003"
    env_file:
      - .env
    # environment:
    #   - MONGO_URL=mongodb://mongo-service:27017/user-service-db
    # depends_on:
    #   - mongo-service

  # mongo-service:
  #   image: mongo
  #   ports:
  #     - "27018:27017"
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: example
