apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
  namespace: default
spec:
  type: state.mongodb
  version: v1
  metadata:
  - name: connectionString
    value: 'mongodb://root:example@mongo:27017/user-service-db?authSource=admin'
